# Site settings
title: nomad labs
email: info@nomad-labs.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://nomad-labs.com"
exclude:     [README.md, Gemfile, Gemfile.lock, CNAME]
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
gems:
  - jekyll-sitemap
